## Install Numpy

In [ ]:
!pip install numpy

## Import Numpy

In [2]:
import numpy as np

## 1. The basics

### Create a Numpy array

In [3]:
arr = np.empty(shape=(2,2))
arr

array([[3.10503618e+231, 3.10503618e+231],
       [1.48219694e-323, 0.00000000e+000]])

In [6]:
arr = np.zeros(shape=(2,2),dtype = 'int32')
arr

array([[0, 0],
       [0, 0]], dtype=int32)

In [8]:
arr = np.arange(2,10,0.1)
#len(arr)
arr

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5,
       4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8,
       5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1,
       7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4,
       8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7,
       9.8, 9.9])

In [9]:
arr.size

80

In [10]:
arr.shape

(80,)

In [11]:
arr.ndim

1

In [12]:
arr.dtype

dtype('float64')

In [15]:
a = np.array([1,2,3], dtype='int32')
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [13]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


### Get dimension

In [16]:
print(a.ndim)
print(b.ndim)

1
2


### Get shape

In [17]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


### Get type

In [18]:
print(a.dtype)
print(b.dtype)

int32
float64


### Get number of elements

In [19]:
print(a.size)
print(b.size)

3
6


## 2. Accessing/Changing elements

In [20]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
c.shape

(2, 7)

In [22]:
c[0 , -1:-7:-2]

array([7, 5, 3])

In [23]:
c[1,5]

13

### Access a specific element

In [ ]:
# [row, column]

In [24]:
c[1,2]

10

### Access a specific row/column

In [25]:
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
c[0]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
c[:, -1]

array([ 7, 14])

### Access elements by steps

In [ ]:
### [start_index : end_index : step_size]
c[1,2:-1:2]

### Change elements

In [ ]:
c[1,5] = 1000
print(c)

In [ ]:
c[:, 2] = [2000, 3000]
print(c)

In [ ]:
c[0, 3:-1] = [4000, 5000, 6000]
print(c)

In [ ]:
print(c)

In [ ]:
c[:,2] = [999, 998]
print(c)

In [ ]:
# Example for a 3D array
d = np.array([[[1,2,3], [3,5,3]], 
              [[5,6,3], [7,8,4]]])
print(d)

In [ ]:
d.shape

In [ ]:
d[1,1,3]

In [ ]:
d[0,0,2]

In [ ]:
d.shape

In [ ]:
d.ndim

In [ ]:
d.size

In [ ]:
# To access a 3D array's element, count outside in
d[1,0,0]

In [ ]:
# Change element of a 3D array
d[:,:,1] = 999
print(d)

In [ ]:
arr = np.arange(3)
arr

In [ ]:
arr + 5

### Repeat an array

In [ ]:
d = np.array([[[1,2,3], 
              [5,6,3]]])

In [ ]:
#(1, 2, 3)
d.shape

In [ ]:
arr = np.array([[1,3,5,7], [2,4,6,8]])
print(np.repeat(a=arr, repeats=4))
print(np.repeat(a=arr, repeats=4, axis=0))
print(np.repeat(a=arr, repeats=4, axis=1))

### Copy an array

In [ ]:
ori = np.array([24,12,2019])
copied = ori.copy()
copied[-1] = 1903

print(ori)
print(copied)

## 3. Initialize different types of array

### All 1s matrix

In [28]:
one_matrix = np.ones(shape=(4,5))
print(one_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### All 0s matrix

In [31]:
zero_matrix= np.zeros(shape=(2,5))
print(zero_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Any number matrix

In [32]:
ninenine_matrix = np.full(shape=(3,6),fill_value=777, dtype='float32')
print(ninenine_matrix)

[[777. 777. 777. 777. 777. 777.]
 [777. 777. 777. 777. 777. 777.]
 [777. 777. 777. 777. 777. 777.]]


### Any number matrix (full_like)

In [33]:
blueprint = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(blueprint)

seven_matrix = np.full_like(a=blueprint, fill_value=7)
print(seven_matrix)

another_seven_matrix = np.full(shape=blueprint.shape, fill_value=7)
print(another_seven_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [34]:
arr

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5,
       4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8,
       5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1,
       7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4,
       8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7,
       9.8, 9.9])

In [35]:
new_arr = np.full_like(a=arr, fill_value=2)
new_arr

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [36]:
new_arr = np.zeros_like(arr)
new_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Identity matrix

In [37]:
i_matrix = np.identity(n=5)
print(i_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Random decimal number array

In [ ]:
random_array = np.random.rand(3,4)
print(random_array)

### Random integer array

In [ ]:
print(np.random.randint(low=-110, high=200, size=(3,6)))

## 4. Mathematics & Statistics

### Simple calculations

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array(object=[9,8,7,6,5,4,3,2,1])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2 - 2*b)

### Linear algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.dot(a,b)

### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])

print(np.min(stats))
print(np.max(stats))
print(np.sum(stats))

In [ ]:
print(np.min(stats, axis=1))
print(np.max(stats, axis=1))

## 5. Reorganizing array

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,-1))
print(after)

### Vertically stacking vectors

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack(tup=(v1,v2,v1,v2))

### Horizontally stacking vectors

In [ ]:
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

np.hstack(tup=(h1,h2,h2,h2))

## 6. Boolean masking and advanced indexing

In [ ]:
arr = np.random.randint(low=1, high=20, size=(8,5))
print(arr)

In [ ]:
bool_mask = arr > 10
print(bool_mask)

In [ ]:
# Get index where have value = True
np.where(bool_mask)

In [ ]:
# Get values that have value >10
larger_than_10 = arr[arr > 10]
print(larger_than_10)

In [ ]:
# Get different values
np.unique(arr)

In [ ]:
len(np.unique(arr))